src/OneStop/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using OneStop.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace OneStop.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        public ApplicationDbContext _db;
        public UserManager<ApplicationUser> _userManager;
        public RoleManager<IdentityRole> _roleManager;

        public RolesController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToString().ToUpper();
            _db.Roles.Add(role);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(string roleId)
        {
            var thisRole = _db.Roles.Where(r => r.Id.Equals(roleId, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(thisRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IdentityRole role)
        {
            try
            {
                var thisRole = _db.Roles.Where(r => r.Id.Equals(role.Id, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                _db.Roles.Attach(thisRole);
                thisRole.Name = role.Name;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View(role);
            }
        }

        public IActionResult Delete(string RoleName)
        {
            var thisRole = _db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(thisRole);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteRole(string RoleName)
        {
            var thisRole = _db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            _db.Roles.Remove(thisRole);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Assign()
        {
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string UserName, string RoleName)
        {
            var user = await _userManager.FindByNameAsync(UserName);
            await _userManager.AddToRoleAsync(user, RoleName);
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ViewBag.RolesForThisUser = await _userManager.GetRolesAsync(await _userManager.FindByNameAsync(UserName));
            }
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View("Assign");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string UserName, string RoleName)
        {
            var user = await _userManager.FindByNameAsync(UserName);

            if (await _userManager.IsInRoleAsync(user, RoleName))
            {
                await _userManager.RemoveFromRoleAsync(user, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View("Assign");
        }
    }
}

src/OneStop/Views/Roles/Assign.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Manage User Roles";
}

<h2>Manage User Roles</h2>

<h2>Role Add to User</h2>

@using (Html.BeginForm("AddRole", "Roles"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.DropDownList("UserName", "Select User")
        Role Name: @Html.DropDownList("RoleName", "Select Roles")
    </p>
    <input type="submit" value="Save" />
}

<hr />
<h3>Get Roles for a User</h3>
@using (Html.BeginForm("GetRoles", "Roles"))
{
    @Html.AntiForgeryToken()
    <p>
        Username : @Html.DropDownList("UserName", "Select User")
        <input type="submit" value="Get Roles for this User" />
    </p>
}

@if (ViewBag.RolesForThisUser != null)
{
    <div>
        <h3>Roles for this user </h3>
        <ol>
            @foreach (string s in ViewBag.RolesForThisUser)
            {
                <li>@s</li>
            }
        </ol>
    </div>
}

<hr />
<h3>Delete A User from a Role</h3>

@using (Html.BeginForm("DeleteRole", "Roles"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.DropDownList("UserName", "Select User")
        Role Name: @Html.DropDownList("RoleName", "Select Roles")
    </p>

    <input type="submit" value="Delete this user from Role" />
}

src/OneStop/Views/Roles/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole

<h2>Create Role</h2>
@Html.ActionLink("List Roles", "Index") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        Role name
    </div>
    <p>
        @Html.TextBoxFor(model => model.Name)
    </p>
    <input type="submit" value="Save" />
}

src/OneStop/Views/Roles/Delete.cshtml
@{
    ViewData["Title"] = "Delete ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole

<h5>Confirm deletion</h5>
<div class="well">
    <h4>Name: @Html.DisplayFor(model => model.Name)</h4>

</div>
@using (Html.BeginForm())
{
    <input type="submit" class="btn btn-danger" value="Delete">
}

src/OneStop/Views/Roles/Edit.cshtml
@{
    ViewData["Title"] = "Edit " + @Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole

<div class="panel panel-success">
    <div class="panel-heading">Detail</div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                <label>Id:</label>
                @Html.DisplayFor(model => model.Id)
                <label>Name:</label>
                <h4> @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })</h4>
                <input type="submit" class="btn btn-success" value="Save Edit">
            </div>
        }
    </div>
</div>

src/OneStop/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole>
@{
    ViewBag.Title = "Roles Listing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @foreach (var role in Model)
    {
        <p>
            <strong>@role.Name | </strong>
            <button class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { roleName = @role.Name })</button>
            <button class="btn btn-info">@Html.ActionLink("Edit", "Edit", new { roleId = @role.Id })</button>
        </p>
    }
</div>

@Html.ActionLink("Create Roles", "Create")
@Html.ActionLink("Assign User Role", "Assign")